samba_packages:
- acl 
- attr 
- samba 
- samba-dsdb-modules 
- samba-vfs-modules 
- winbind 
- libpam-winbind 
- libnss-winbind 
- libpam-krb5 
- krb5-config 
- krb5-user
- dnsutils
- smbclient

samba_tdb_files:
- /run/samba/names.tdb
- /run/samba/gencache.tdb
- /var/lib/samba/private/secrets.tdb
- /var/lib/samba/private/sam.ldb.d/metadata.tdb
- /var/lib/samba/share_info.tdb

samba_configuration_files:
- /etc/samba/smb.conf
- /etc/krb5.conf

samba_realm: A2CORP.COM.BR
samba_workgroup: A2CORP
samba_netbios_name: KLN02
samba_password: Admin123@