---
- name: Install samba packages
  apt:
    name: "{{ item }}"
  loop: "{{ samba_packages }}"

- name: Change hostname
  hostname:
    name: "{{ samba_netbios_name }}"
    use: systemd

- name: Create a fresh /etc/hosts with new hostname
  template:
    src: templates/hosts.j2
    dest: /etc/hosts

- name: make sure the configuration files don't exist
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ samba_configuration_files }}"

- name: Remove database files
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ samba_tdb_files }}"

- name: Disable systemd-resolve service
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
    masked: yes

- name: Create a fresh /etc/resolv.conf
  template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf

- name: Create a fresh /etc/krb5.conf
  template:
    src: templates/krb5.conf.j2
    dest: /etc/krb5.conf

- name: Create a fresh smb.conf
  template:
    src: templates/smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: restart samba

- name: Join AD
  shell:
    net ads join -U administrator%'{{samba_password}}'


