- name: restart openvas
  systemd:
    daemon_reload: yes
    state: restarted
    enabled: yes
    name: "{{ item }}"
  with_items:
  - greenbone-security-assistant
  - openvas-manager
  - openvas-scanner
    