- name: Configure samba AD-DC
  hosts: samba-ad-dc
  become: yes
  gather_facts: no
  roles:
    - samba-ad-dc

# - name: Configure samba file server
#   hosts: samba-fileserver
#   become: yes
#   gather_facts: no
#   roles:
#     - partition
#     - samba-fileserver