- name: Configure samba AD-DC
  hosts: samba-ad-dc
  become: yes
  roles:
    - samba-ad-dc

- name: Configure samba file server
  hosts: samba-fileserver
  become: yes
  roles:
    - partition
    - samba-fileserver