# - name: Configure samba AD-DC
#   hosts: samba-ad-dc
#   become: yes
#   roles:
#     - samba-ad-dc

# - name: Configure samba file server
#   hosts: samba-fileserver
#   become: yes
#   roles:
#     - partition
#     - samba-fileserver

# - name: Install GLPI
#   hosts: glpi
#   become: yes
#   roles:
#     - glpi

# # - name: Install urbackup
# #   hosts: urbackup
# #   become: yes
# #   roles:
# #     - urbackup

# - name: Install rocketchat
#   hosts: rocketchat
#   become: yes
#   roles:
#     - rocketchat

- name: Install openvas
  hosts: openvas
  become: yes
  roles:
    - openvas